# Generated by Django 6.0.7 on 2026-07-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_clickanalytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='longtoshort',
            name='country_clicks',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='longtoshort',
            name='desktop_clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='longtoshort',
            name='last_clicked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='longtoshort',
            name='last_country',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='longtoshort',
            name='last_device',
            field=models.CharField(default='Desktop', max_length=20),
        ),
        migrations.AddField(
            model_name='longtoshort',
            name='mobile_clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ClickAnalytics',
        ),
    ]
